#!/usr/bin/env bash

die() {
    echo "$@" >&2
    exit 1
}

TABLE_NAME=
COL_HEAD=

# get table name
if [ -n "$1" ]; then
    TABLE_NAME="$1"
else
    die "requires one argument, table name"
fi

# read first line of input
read -r COL_HEAD

while read -r; do
    echo "INSERT INTO $TABLE_NAME ($COL_HEAD) VALUES "
done
